import os

from fontTools.misc.transform import Identity
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

FD = os.path.expanduser("~/Library/Fonts")
SOLID = os.path.join(FD, "Font Awesome 6 Free-Solid-900.otf")
BRANDS = os.path.join(FD, "Font Awesome 6 Brands-Regular-400.otf")

WANT = {
    SOLID: {
        "envelope": 0xF0E0,
        "home": 0xF015,
        "scholar": 0xF19D,
        "briefcase": 0xF0B1,
        "education": 0xF19D,
        "gear": 0xF013,
        "book": 0xF02D,
        "award": 0xF559,
        "users": 0xF0C0,
        "external": 0xF08E,
    },
    BRANDS: {"github": 0xF09B, "linkedin": 0xF08C},
}

OUT = "icons"
os.makedirs(OUT, exist_ok=True)

# Each file carries the glyph's OWN tight bounding box as its viewBox. The shared
# box that makes every icon scale identically is computed by build.mjs at load
# time, across whatever files are present, so adding an icon rescales the whole set
written = []
for path, wants in WANT.items():
    f = TTFont(path)
    cmap = f.getBestCmap()
    gs = f.getGlyphSet()
    for name, cp in sorted(wants.items()):
        gname = cmap.get(cp)
        if gname is None:
            print("MISS", name, hex(cp))
            continue
        bp = BoundsPen(gs)
        gs[gname].draw(bp)
        x0, y0, x1, y1 = bp.bounds
        # flip y for SVG coords, so the tight box is x:[x0,x1], y:[-y1,-y0]
        sp = SVGPathPen(gs)
        gs[gname].draw(TransformPen(sp, Identity.scale(1, -1)))
        vb = f"{x0} {-y1} {x1 - x0} {y1 - y0}"
        with open(os.path.join(OUT, f"{name}.svg"), "w") as fh:
            fh.write(
                "<!-- generated by tools/extract-icons.py from Font Awesome 6; "
                "viewBox is the glyph's tight bbox, normalized at build time -->\n"
                f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{vb}">'
                f'<path d="{sp.getCommands()}"/></svg>\n'
            )
        written.append((name, x1 - x0, y1 - y0))
        print(f"ok {name:10s} bbox={x0:.0f},{y0:.0f} {x1:.0f},{y1:.0f}")

SIDE = max(max(w, h) for _, w, h in written)
print(
    f"\n{len(written)} icons -> {OUT}/   (build.mjs will use a {SIDE:.0f}-unit shared box)"
)
for name, w, h in sorted(written):
    print(f"  {name:10s} renders at {h / SIDE:.2f} x box height")
